name : Diginamic - Approche Impérative

permissions: write-all

on:
  push:
  workflow_dispatch:

jobs:
  build:
    - name: Utilisation package
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/DiginamicFormation/outillage-check-exercices" }]'
      
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: test with Maven
        run : mvn clean test
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Rapport d'exécution des tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
