name : Diginamic - Approche Impérative

permissions: write-all

on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
      
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
          server-id: outillage-check-exercices
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: install with Maven
        run : mvn install
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: test with Maven
        run : mvn clean test
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Rapport d'exécution des tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
